// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: pet.sql

package db

import (
	"context"
	"database/sql"
)

const insertNewPet = `-- name: InsertNewPet :exec
INSERT INTO mascotas (
    propietario_id,
    raza_id,
    token,
    descripcion,
    nombre,
    edad_aprox
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertNewPetParams struct {
	PropietarioID sql.NullInt32  `json:"propietario_id"`
	RazaID        sql.NullInt32  `json:"raza_id"`
	Token         string         `json:"token"`
	Descripcion   sql.NullString `json:"descripcion"`
	Nombre        sql.NullString `json:"nombre"`
	EdadAprox     sql.NullInt32  `json:"edad_aprox"`
}

func (q *Queries) InsertNewPet(ctx context.Context, arg InsertNewPetParams) error {
	_, err := q.db.ExecContext(ctx, insertNewPet,
		arg.PropietarioID,
		arg.RazaID,
		arg.Token,
		arg.Descripcion,
		arg.Nombre,
		arg.EdadAprox,
	)
	return err
}
