// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: pet.sql

package db

import (
	"context"
	"database/sql"
)

const insertNewPet = `-- name: InsertNewPet :exec
INSERT INTO mascotas (
    propietario_id,
    raza_id,
    raza_comentario,
    nombre,
    edad
) VALUES (?, ?, ?, ?, ?)
`

type InsertNewPetParams struct {
	PropietarioID  sql.NullInt32  `json:"propietario_id"`
	RazaID         sql.NullInt32  `json:"raza_id"`
	RazaComentario sql.NullString `json:"raza_comentario"`
	Nombre         sql.NullString `json:"nombre"`
	Edad           sql.NullInt32  `json:"edad"`
}

func (q *Queries) InsertNewPet(ctx context.Context, arg InsertNewPetParams) error {
	_, err := q.db.ExecContext(ctx, insertNewPet,
		arg.PropietarioID,
		arg.RazaID,
		arg.RazaComentario,
		arg.Nombre,
		arg.Edad,
	)
	return err
}
