// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: race.sql

package db

import (
	"context"
	"database/sql"
)

const selectRacesByFamily = `-- name: SelectRacesByFamily :many
SELECT id, nombre
FROM razas
WHERE familia_id = ?
`

type SelectRacesByFamilyRow struct {
	ID     int32          `json:"id"`
	Nombre sql.NullString `json:"nombre"`
}

func (q *Queries) SelectRacesByFamily(ctx context.Context, familiaID sql.NullInt32) ([]SelectRacesByFamilyRow, error) {
	rows, err := q.db.QueryContext(ctx, selectRacesByFamily, familiaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectRacesByFamilyRow
	for rows.Next() {
		var i SelectRacesByFamilyRow
		if err := rows.Scan(&i.ID, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
