// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: vet_place.sql

package db

import (
	"context"
)

const checkVetPlaceNameExists = `-- name: CheckVetPlaceNameExists :one
SELECT COUNT(*)
FROM negocios
WHERE nombre_negocio = ?
`

func (q *Queries) CheckVetPlaceNameExists(ctx context.Context, nombreNegocio string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkVetPlaceNameExists, nombreNegocio)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteVetPlace = `-- name: DeleteVetPlace :exec
UPDATE negocios
SET fecha_delete = DATE_SUB(NOW(), INTERVAL 6 HOUR)
WHERE id = ?
`

func (q *Queries) DeleteVetPlace(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteVetPlace, id)
	return err
}

const insertNewVetPlace = `-- name: InsertNewVetPlace :exec
INSERT INTO negocios (nombre_negocio, token)
VALUES (?, ?)
`

type InsertNewVetPlaceParams struct {
	NombreNegocio string `json:"nombre_negocio"`
	Token         string `json:"token"`
}

func (q *Queries) InsertNewVetPlace(ctx context.Context, arg InsertNewVetPlaceParams) error {
	_, err := q.db.ExecContext(ctx, insertNewVetPlace, arg.NombreNegocio, arg.Token)
	return err
}

const updateVetPlace = `-- name: UpdateVetPlace :exec
UPDATE negocios
SET nombre_negocio = ?
WHERE id = ?
`

type UpdateVetPlaceParams struct {
	NombreNegocio string `json:"nombre_negocio"`
	ID            int32  `json:"id"`
}

func (q *Queries) UpdateVetPlace(ctx context.Context, arg UpdateVetPlaceParams) error {
	_, err := q.db.ExecContext(ctx, updateVetPlace, arg.NombreNegocio, arg.ID)
	return err
}
