DROP PROCEDURE IF EXISTS `getUserByEmail`;
DROP PROCEDURE IF EXISTS `getVetByEmail`;
DROP PROCEDURE IF EXISTS `getVetMainInfoById`;
DROP PROCEDURE IF EXISTS `insertNewVet`;
DROP PROCEDURE IF EXISTS `checkVetEmailExists`;
DROP PROCEDURE IF EXISTS `updateVet`;
DROP PROCEDURE IF EXISTS `deleteVet`;